IF OBJECT_ID ('ATL_ENTREGA_LEVANTA','U') IS NOT NULL
    DROP TABLE dbo.ATL_ENTREGA_LEVANTA;
IF OBJECT_ID ('ATL_PARTICIPA','U') IS NOT NULL
    DROP TABLE dbo.ATL_PARTICIPA;
IF OBJECT_ID ('ATL_REALIZA','U') IS NOT NULL
    DROP TABLE dbo.ATL_REALIZA;
IF OBJECT_ID ('ATL_TURMA_CLASSE','U') IS NOT NULL
    DROP TABLE dbo.ATL_TURMA_CLASSE;
IF OBJECT_ID ('ATL_ALUNO','U') IS NOT NULL
    DROP TABLE dbo.ATL_ALUNO;
IF OBJECT_ID ('ATL_TURMA','U') IS NOT NULL
    DROP TABLE dbo.ATL_TURMA;
IF OBJECT_ID ('ATL_PESSOA_AUTORIZADA','U') IS NOT NULL
    DROP TABLE dbo.ATL_PESSOA_AUTORIZADA;
IF OBJECT_ID ('ATL_ENCARREGADO_EDUCACAO','U') IS NOT NULL
    DROP TABLE dbo.ATL_ENCARREGADO_EDUCACAO;
IF OBJECT_ID ('ATL_PROFESSOR','U') IS NOT NULL
    DROP TABLE dbo.ATL_PROFESSOR;
IF OBJECT_ID ('ATL_ATIVIDADE','U') IS NOT NULL
    DROP TABLE dbo.ATL_ATIVIDADE;
IF OBJECT_ID ('ATL_PESSOA','U') IS NOT NULL
    DROP TABLE dbo.ATL_PESSOA;

CREATE TABLE ATL_PESSOA (
	NOME				VARCHAR(30)	NOT NULL,
	TELEFONE			INT,
	EMAIL				VARCHAR(30),
	DATA_DE_NASCIMENTO	DATE		NOT NULL,
	MORADA				VARCHAR(30)	NOT NULL,
	CARTAO_CIDADAO		INT			NOT NULL,
	PRIMARY KEY (CARTAO_CIDADAO)
);

CREATE TABLE ATL_ATIVIDADE (
	IDENTIFICADOR		INT			NOT NULL,
	CUSTO_FINANCEIRO	INT			NOT	NULL,
	DESIGNACAO			VARCHAR(20)	NOT NULL,
	PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE ATL_PROFESSOR (
	NUMERO_FUNC		INT		NOT NULL,
	CARTAO_CIDADAO	INT		NOT NULL,
	PRIMARY KEY (CARTAO_CIDADAO),
	FOREIGN KEY (CARTAO_CIDADAO) REFERENCES ATL_PESSOA (CARTAO_CIDADAO)
);

CREATE TABLE ATL_ENCARREGADO_EDUCACAO (
	RELACAO_COM_ALUNO	VARCHAR(20)	NOT NULL,
	CARTAO_CIDADAO		INT			NOT NULL,
	PRIMARY KEY (CARTAO_CIDADAO),
	FOREIGN KEY (CARTAO_CIDADAO) REFERENCES ATL_PESSOA (CARTAO_CIDADAO)
);

CREATE TABLE ATL_PESSOA_AUTORIZADA (
	CARTAO_CIDADAO		INT		NOT NULL,
	PRIMARY KEY (CARTAO_CIDADAO),
	FOREIGN KEY (CARTAO_CIDADAO) REFERENCES ATL_PESSOA (CARTAO_CIDADAO)
);

CREATE TABLE ATL_TURMA (
	IDENTIFICADOR		INT			NOT NULL,
	ANO_LETIVO			INT			NOT NULL,
	DESIGNACAO			VARCHAR(20)	NOT NULL,
	NUMERO_MAX_ALUNOS	INT			NOT NULL,
	PROFESSOR_CC		INT			NOT NULL,
	PRIMARY KEY (IDENTIFICADOR),
	FOREIGN KEY	(PROFESSOR_CC) REFERENCES ATL_PROFESSOR (CARTAO_CIDADAO)
);

CREATE TABLE ATL_ALUNO (
	NOME 				VARCHAR(30)	NOT NULL,
	MORADA				VARCHAR(30)	NOT NULL,
	DATA_DE_NASCIMENTO	DATE		NOT NULL,
	CARTAO_CIDADAO		INT			NOT NULL,
	IDENTIFICADOR_TURMA	INT			NOT NULL,
	CARTAO_CIDADAO_EE	INT			NOT NULL,
	PRIMARY KEY (CARTAO_CIDADAO),
	FOREIGN KEY (IDENTIFICADOR_TURMA) REFERENCES ATL_TURMA (IDENTIFICADOR),
	FOREIGN KEY (CARTAO_CIDADAO_EE) REFERENCES ATL_ENCARREGADO_EDUCACAO (CARTAO_CIDADAO)
);

CREATE TABLE ATL_TURMA_CLASSE (
	T_CLASSE 			INT 	NOT NULL,
	IDENTIFICADOR_TURMA	INT		NOT NULL,
	PRIMARY KEY (IDENTIFICADOR_TURMA),
	FOREIGN KEY (IDENTIFICADOR_TURMA) REFERENCES ATL_TURMA (IDENTIFICADOR)
);

CREATE TABLE ATL_REALIZA (
	IDENTIFICADOR_ATIVIDADE	INT		NOT NULL,
	IDENTIFICADOR_TURMA		INT		NOT NULL,
	PRIMARY KEY (IDENTIFICADOR_ATIVIDADE, IDENTIFICADOR_TURMA),
	FOREIGN KEY (IDENTIFICADOR_ATIVIDADE) REFERENCES ATL_ATIVIDADE (IDENTIFICADOR),
	FOREIGN KEY (IDENTIFICADOR_TURMA) REFERENCES ATL_TURMA (IDENTIFICADOR)
);

CREATE TABLE ATL_PARTICIPA (
	IDENTIFICADOR_ATIVIDADE	INT		NOT NULL,
	ALUNO_CC				INT		NOT NULL,
	PRIMARY KEY (IDENTIFICADOR_ATIVIDADE, ALUNO_CC),
	FOREIGN KEY (IDENTIFICADOR_ATIVIDADE) REFERENCES ATL_ATIVIDADE (IDENTIFICADOR),
	FOREIGN KEY (ALUNO_CC) REFERENCES ATL_ALUNO (CARTAO_CIDADAO)
);

CREATE TABLE ATL_ENTREGA_LEVANTA (
	PESSOA_A_CC		INT		NOT NULL,
	ALUNO_CC		INT		NOT NULL,
	PRIMARY KEY (PESSOA_A_CC, ALUNO_CC),
	FOREIGN KEY (PESSOA_A_CC) REFERENCES ATL_PESSOA_AUTORIZADA (CARTAO_CIDADAO),
	FOREIGN KEY (ALUNO_CC) REFERENCES ATL_ALUNO (CARTAO_CIDADAO)
);