IF OBJECT_ID ('CONF_TEM','U') IS NOT NULL
    DROP TABLE dbo.CONF_TEM;
IF OBJECT_ID ('CONF_AUTOR','U') IS NOT NULL
    DROP TABLE dbo.CONF_AUTOR;
IF OBJECT_ID ('CONF_ESTUDANTE','U') IS NOT NULL
    DROP TABLE dbo.CONF_ESTUDANTE;
IF OBJECT_ID ('CONF_PARTICIPANTE','U') IS NOT NULL
    DROP TABLE dbo.CONF_PARTICIPANTE;
IF OBJECT_ID ('CONF_NAO_ESTUDANTE','U') IS NOT NULL
    DROP TABLE dbo.CONF_NAO_ESTUDANTE;
IF OBJECT_ID ('CONF_PESSOA','U') IS NOT NULL
    DROP TABLE dbo.CONF_PESSOA;
IF OBJECT_ID ('CONF_ARTIGO','U') IS NOT NULL
    DROP TABLE dbo.CONF_ARTIGO;
IF OBJECT_ID ('CONF_INSTITUICAO','U') IS NOT NULL
    DROP TABLE dbo.CONF_INSTITUICAO;

CREATE TABLE CONF_INSTITUICAO (
	ENDERECO	VARCHAR(30)		NOT NULL,
	NOME		VARCHAR(25)		NOT NULL,
	PRIMARY KEY (ENDERECO)
);

CREATE TABLE CONF_ARTIGO (
	NUMERO_REGISTO		INT			NOT NULL,
	TITULO				VARCHAR(20)	NOT NULL,
	PRIMARY KEY (NUMERO_REGISTO)
);

CREATE TABLE CONF_PESSOA (
	NOME					VARCHAR(25)	NOT NULL,
	EMAIL					VARCHAR(30)	NOT NULL,
	INSTITUICAO_ENDERECO	VARCHAR(30)	NOT NULL,
	PRIMARY KEY (EMAIL),
	FOREIGN KEY (INSTITUICAO_ENDERECO) REFERENCES CONF_INSTITUICAO (ENDERECO)
);

CREATE TABLE CONF_NAO_ESTUDANTE (
	REFERENCIA		INT			NOT NULL,
	EMAIL			VARCHAR(30)	NOT NULL,
	PRIMARY KEY (EMAIL),
	FOREIGN KEY (EMAIL) REFERENCES CONF_PESSOA (EMAIL)
);

CREATE TABLE CONF_PARTICIPANTE (
	MORADA				VARCHAR(30)	NOT NULL,
	DATA_DE_INSCRICAO	DATE		NOT NULL,
	EMAIL				VARCHAR(30)	NOT NULL,
	PRIMARY KEY (EMAIL),
	FOREIGN KEY (EMAIL) REFERENCES CONF_PESSOA (EMAIL)
);

CREATE TABLE CONF_ESTUDANTE (
	LOCALIZACAO				VARCHAR(30)	NOT NULL,
	INSTITUICAO_ENDERECO	VARCHAR(30)	NOT NULL,
	EMAIL					VARCHAR(30)	NOT NULL,
	PRIMARY KEY (EMAIL),
	FOREIGN KEY (EMAIL) REFERENCES CONF_PESSOA (EMAIL),
	FOREIGN KEY (INSTITUICAO_ENDERECO) REFERENCES CONF_INSTITUICAO (ENDERECO)
);

CREATE TABLE CONF_AUTOR (
	EMAIL	VARCHAR(30)	NOT NULL,
	PRIMARY KEY (EMAIL),
	FOREIGN KEY (EMAIL) REFERENCES CONF_PESSOA (EMAIL),
);

CREATE TABLE CONF_TEM (
	AUTOR_EMAIL		VARCHAR(30)	NOT NULL,
	NUMERO_REGISTO	INT			NOT NULL,
	PRIMARY KEY (AUTOR_EMAIL, NUMERO_REGISTO),
	FOREIGN KEY (AUTOR_EMAIL) REFERENCES CONF_AUTOR (EMAIL),
	FOREIGN KEY (NUMERO_REGISTO) REFERENCES CONF_ARTIGO (NUMERO_REGISTO)
);