IF OBJECT_ID ('MEDICAMENTOS_PRODUZ','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_PRODUZ;
IF OBJECT_ID ('MEDICAMENTOS_PRESCRICAO_TEM_FARMACO','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_PRESCRICAO_TEM_FARMACO;
IF OBJECT_ID ('MEDICAMENTOS_VENDA','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_VENDA;
IF OBJECT_ID ('MEDICAMENTOS_PRESCRICAO','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_PRESCRICAO;
IF OBJECT_ID ('MEDICAMENTOS_FARMACEUTICA','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_FARMACEUTICA;
IF OBJECT_ID ('MEDICAMENTOS_FARMACO','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_FARMACO;
IF OBJECT_ID ('MEDICAMENTOS_FARMACIA','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_FARMACIA;
IF OBJECT_ID ('MEDICAMENTOS_PACIENTE','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_PACIENTE;
IF OBJECT_ID ('MEDICAMENTOS_MEDICO','U') IS NOT NULL
    DROP TABLE dbo.MEDICAMENTOS_MEDICO;

CREATE TABLE MEDICAMENTOS_MEDICO (
    SNS             INT         NOT NULL,
    NOME            VARCHAR(20) NOT NULL,
    ESPECIALIDADE   VARCHAR(15) NOT NULL,
    PRIMARY KEY (SNS),
);

CREATE TABLE MEDICAMENTOS_PACIENTE(
    NUMERO_UTENTE   INT         NOT NULL,
    NOME            VARCHAR(20) NOT NULL,
    ENDERECO        VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE        NOT NULL,
    PRIMARY KEY (NUMERO_UTENTE),
);

CREATE TABLE MEDICAMENTOS_FARMACIA(
    NIF         INT         NOT NULL,
    NOME        VARCHAR(20) NOT NULL,
    ENDERECO    VARCHAR(20) NOT NULL,
    TELEFONE    INT         NOT NULL,
    PRIMARY KEY (NIF),
);

CREATE TABLE MEDICAMENTOS_FARMACO(
    FORMULA         VARCHAR(20) NOT NULL,
    NOME_COMERCIAL  VARCHAR(20) NOT NULL,
    PRIMARY KEY (FORMULA),
);

CREATE TABLE MEDICAMENTOS_FARMACEUTICA(
    NUMERO_NACIONAL INT         NOT NULL,
    TELEFONE        INT         NOT NULL,
    ENDERECO        VARCHAR(20) NOT NULL,
    NOME            VARCHAR(20) NOT NULL,
    PRIMARY KEY (NUMERO_NACIONAL)
);

CREATE TABLE MEDICAMENTOS_PRESCRICAO(
    NUMERO                  INT     NOT NULL,
    PRESCRICAO_DATA         DATE    NOT NULL,
    MEDICO_SNS              INT     NOT NULL,
    PACIENTE_NUMERO_UTENTE  INT     NOT NULL,
    PRIMARY KEY (NUMERO),
    FOREIGN KEY (MEDICO_SNS)                REFERENCES MEDICAMENTOS_MEDICO,
    FOREIGN KEY (PACIENTE_NUMERO_UTENTE)    REFERENCES MEDICAMENTOS_PACIENTE,
);

CREATE TABLE MEDICAMENTOS_VENDA(
    FARMACIA_NIF    INT         NOT NULL,
    FARMACO_FORMULA VARCHAR(20) NOT NULL,
    PRIMARY KEY (FARMACIA_NIF, FARMACO_FORMULA),
    FOREIGN KEY (FARMACIA_NIF)      REFERENCES MEDICAMENTOS_FARMACIA,
    FOREIGN KEY (FARMACO_FORMULA)   REFERENCES MEDICAMENTOS_FARMACO,
);

CREATE TABLE MEDICAMENTOS_PRESCRICAO_TEM_FARMACO(
    PRESCRICAO_NUMERO   INT NOT NULL,
    FARMACO_FORMULA     VARCHAR(20) NOT NULL,
    PRIMARY KEY (PRESCRICAO_NUMERO, FARMACO_FORMULA),
    FOREIGN KEY (PRESCRICAO_NUMERO) REFERENCES  MEDICAMENTOS_PRESCRICAO,
    FOREIGN KEY (FARMACO_FORMULA)   REFERENCES MEDICAMENTOS_FARMACO,
);

CREATE TABLE MEDICAMENTOS_PRODUZ(
    FARMACEUTICA_NUMERO_NACIONAL    INT         NOT NULL,
    FARMACO_FORMULA                 VARCHAR(20) NOT NULL,
    PRIMARY KEY (FARMACEUTICA_NUMERO_NACIONAL, FARMACO_FORMULA),
    FOREIGN KEY (FARMACEUTICA_NUMERO_NACIONAL)  REFERENCES  MEDICAMENTOS_FARMACEUTICA,
    FOREIGN KEY (FARMACO_FORMULA)               REFERENCES MEDICAMENTOS_FARMACO,
);