IF OBJECT_ID ('RENT_ALUGUER','U') IS NOT NULL
    DROP TABLE dbo.RENT_ALUGUER;
IF OBJECT_ID ('RENT_CLIENTE','U') IS NOT NULL
    DROP TABLE dbo.RENT_CLIENTE;
IF OBJECT_ID ('RENT_BALCAO','U') IS NOT NULL
    DROP TABLE dbo.RENT_BALCAO;
IF OBJECT_ID ('RENT_VEICULO','U') IS NOT NULL
    DROP TABLE dbo.RENT_VEICULO;
IF OBJECT_ID ('RENT_LIGEIRO','U') IS NOT NULL
    DROP TABLE dbo.RENT_LIGEIRO;
IF OBJECT_ID ('RENT_PESADO','U') IS NOT NULL
    DROP TABLE dbo.RENT_PESADO;
IF OBJECT_ID ('RENT_SIMILARIEDADE','U') IS NOT NULL
    DROP TABLE dbo.RENT_SIMILARIEDADE;
IF OBJECT_ID ('RENT_TIPO_VEICULO','U') IS NOT NULL
    DROP TABLE dbo.RENT_TIPO_VEICULO;

CREATE TABLE RENT_CLIENTE (
	NIF			INT			NOT NULL,
	NUM_CARTA	INT			NOT NULL,		
	ENDERECO	VARCHAR(30) NOT NULL,
	NOME		VARCHAR(15)	NOT NULL,
	PRIMARY KEY (NIF),
	UNIQUE (NUM_CARTA)
);

CREATE TABLE RENT_BALCAO (
	NUMERO		INT			NOT NULL,
	ENDERECO	VARCHAR(30) NOT NULL,
	NOME		VARCHAR(15) NOT NULL,
	PRIMARY KEY (NUMERO)
);

CREATE TABLE RENT_TIPO_VEICULO (
	CODIGO			INT			NOT NULL,
	DESIGNACAO		VARCHAR(20) NOT NULL,
	ARCONDICIONADO	VARCHAR(5),
	PRIMARY KEY (CODIGO)
);

CREATE TABLE RENT_VEICULO (
	MATRICULA	VARCHAR(10)	NOT NULL,
	MARCA		VARCHAR(15)	NOT NULL,
	ANO			INT			NOT NULL,
	TIPO_CODIGO	INT			NOT NULL,
	PRIMARY KEY (MATRICULA),
	FOREIGN KEY (TIPO_CODIGO) REFERENCES RENT_TIPO_VEICULO (CODIGO)
);

CREATE TABLE RENT_PESADO (
	PESO		DECIMAL(10,2)	NOT NULL,
	PASSAGEIROS	INT				NOT NULL,
	TIPO_CODIGO	INT				NOT	NULL,
	PRIMARY KEY (TIPO_CODIGO),
	FOREIGN KEY (TIPO_CODIGO) REFERENCES RENT_TIPO_VEICULO (CODIGO)
);

CREATE TABLE RENT_LIGEIRO (
	NUM_LUGARES	INT			NOT NULL,
	PORTAS		INT			NOT NULL,
	COMBUSTIVEL	VARCHAR(10)	NOT NULL,
	TIPO_CODIGO	INT			NOT	NULL,
	PRIMARY KEY (TIPO_CODIGO),
	FOREIGN KEY (TIPO_CODIGO) REFERENCES RENT_TIPO_VEICULO (CODIGO)
);

CREATE TABLE RENT_SIMILARIEDADE (
	TIPO_CODIGO1	INT			NOT	NULL,
	TIPO_CODIGO2	INT			NOT	NULL,
	PRIMARY KEY (TIPO_CODIGO1, TIPO_CODIGO2),
	FOREIGN KEY (TIPO_CODIGO1) REFERENCES RENT_TIPO_VEICULO (CODIGO),
	FOREIGN KEY (TIPO_CODIGO2) REFERENCES RENT_TIPO_VEICULO (CODIGO)
);

CREATE TABLE RENT_ALUGUER (
	NUMERO				INT			NOT NULL,
	ALU_DATA			DATE		NOT NULL,
	DURACAO				INT			NOT NULL,
	NIF_CLIENTE			INT			NOT NULL,
	VEICULO_MATRICULA	VARCHAR(10)	NOT NULL,
	BALCAO_NUMERO		INT			NOT NULL,
	PRIMARY KEY (NUMERO),
	FOREIGN KEY (NIF_CLIENTE) REFERENCES RENT_CLIENTE (NIF),
	FOREIGN KEY (VEICULO_MATRICULA) REFERENCES RENT_VEICULO (MATRICULA),
	FOREIGN KEY (BALCAO_NUMERO) REFERENCES RENT_BALCAO (NUMERO),
);