IF OBJECT_ID ('STOCKS_ITEM','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_ITEM;
IF OBJECT_ID ('STOCKS_ENCOMENDA','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_ENCOMENDA;
IF OBJECT_ID ('STOCKS_FORNECEDOR','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_FORNECEDOR;
IF OBJECT_ID ('STOCKS_TIPO_FORNECEDOR','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_TIPO_FORNECEDOR;
IF OBJECT_ID ('STOCKS_CONDICOES_PAGAMENTO','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_CONDICOES_PAGAMENTO;
IF OBJECT_ID ('STOCKS_PRODUTO','U') IS NOT NULL
    DROP TABLE dbo.STOCKS_PRODUTO;

CREATE TABLE STOCKS_PRODUTO (
	CODIGO		INT				NOT NULL,
	PRECO		DECIMAL(10,2)	NOT NULL,
	NOME		VARCHAR(20)		NOT NULL,
	TAXA_IVA	INT,
	QUANTIDADE	INT				NOT NULL,
	PRIMARY KEY (CODIGO),
);

CREATE TABLE STOCKS_CONDICOES_PAGAMENTO(
	PRAZO	DATE	NOT NULL,
	PRIMARY KEY (PRAZO),
);

CREATE TABLE STOCKS_TIPO_FORNECEDOR(
	CODIGO		INT			NOT NULL,
	DESIGNACAO	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (CODIGO),
);

CREATE TABLE STOCKS_FORNECEDOR(
	NIF							INT			NOT NULL,
	NOME						VARCHAR(20) NOT NULL,
	EMAIL						VARCHAR(20),
	MORADA						VARCHAR(20)	NOT NULL,
	CONDICOES_PAGAMENTO_PRAZO	DATE		NOT NULL,
	TIPO_FORNECEDOR_CODIGO		INT			NOT NULL,
	PRIMARY KEY (NIF),
	FOREIGN KEY (CONDICOES_PAGAMENTO_PRAZO) REFERENCES STOCKS_CONDICOES_PAGAMENTO (PRAZO),
	FOREIGN KEY (TIPO_FORNECEDOR_CODIGO)	REFERENCES STOCKS_TIPO_FORNECEDOR (CODIGO),
);

CREATE TABLE STOCKS_ENCOMENDA(
	NUMERO			INT		NOT NULL,
	ENCOMENDA_DATA	DATE	NOT NULL,
	FORNECEDOR_NIF	INT		NOT NULL,
	PRIMARY KEY (NUMERO),
	FOREIGN KEY (FORNECEDOR_NIF)	REFERENCES	STOCKS_FORNECEDOR (NIF),
);

CREATE TABLE STOCKS_ITEM(
	QUANTIDADE			INT	NOT NULL,
	PRODUTO_CODIGO		INT	NOT NULL,
	ENCOMENDA_NUMERO	INT	NOT NULL,
	PRIMARY KEY (QUANTIDADE, PRODUTO_CODIGO),
	FOREIGN KEY (PRODUTO_CODIGO)	REFERENCES	STOCKS_PRODUTO (CODIGO),
	FOREIGN KEY (ENCOMENDA_NUMERO)	REFERENCES	STOCKS_ENCOMENDA (NUMERO),
);