CREATE TABLE VOOS_AIRPORT (
	CODE			INT			NOT NULL,
	CITY			VARCHAR(15) NOT NULL,
	AIRPORT_STATE	VARCHAR(15)	NOT NULL,
	NOME			VARCHAR(15)	NOT NULL,
	PRIMARY KEY (CODE)
);

CREATE TABLE VOOS_AIRPLANE_TYPE (
	VOO_TYPE_NAME	VARCHAR(15)	NOT NULL,
	COMPANY			VARCHAR(20)	NOT NULL,
	MAX_SEATS		INT			NOT NULL,
	PRIMARY KEY (VOO_TYPE_NAME)
);

CREATE TABLE VOOS_FLIGHT (
	NUMBER		INT			NOT NULL,
	AIRLINE		VARCHAR(20)	NOT NULL,
	WEEKDAYS	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (NUMBER)
);

CREATE TABLE VOOS_FARE (
	CODE			INT			NOT NULL,
	FLIGHT_NUMBER	INT			NOT NULL,
	AMOUNT			INT			NOT	NULL,
	RESTRICTIONS	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (CODE, FLIGHT_NUMBER),
	FOREIGN KEY (FLIGHT_NUMBER) REFERENCES VOOS_FLIGHT (NUMBER)
);

CREATE TABLE VOOS_AIRPLANE (
	AIRPLANE_ID			INT			NOT NULL,
	TOTAL_NO_OF_SEATS	INT			NOT NULL,
	AIRPLANE_TYPE_NAME	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (AIRPLANE_ID),
	FOREIGN KEY (AIRPLANE_TYPE_NAME) REFERENCES VOOS_AIRPLANE_TYPE (VOO_TYPE_NAME)
);

CREATE TABLE VOOS_CAN_LAND (
);

CREATE TABLE VOOS_FLIGHT_LEG (
);

CREATE TABLE VOOS_LEGINSTANCE (
);

CREATE TABLE VOOS_SEAT (
);