IF OBJECT_ID ('VOOS_SEAT','U') IS NOT NULL
    DROP TABLE dbo.VOOS_SEAT;
IF OBJECT_ID ('VOOS_LEG_INSTANCE','U') IS NOT NULL
    DROP TABLE dbo.VOOS_LEG_INSTANCE;
IF OBJECT_ID ('VOOS_FLIGHT_LEG','U') IS NOT NULL
    DROP TABLE dbo.VOOS_FLIGHT_LEG;
IF OBJECT_ID ('VOOS_CAN_LAND','U') IS NOT NULL
    DROP TABLE dbo.VOOS_CAN_LAND;
IF OBJECT_ID ('VOOS_AIRPLANE','U') IS NOT NULL
    DROP TABLE dbo.VOOS_AIRPLANE;
IF OBJECT_ID ('VOOS_FARE','U') IS NOT NULL
    DROP TABLE dbo.VOOS_FARE;
IF OBJECT_ID ('VOOS_FLIGHT','U') IS NOT NULL
    DROP TABLE dbo.VOOS_FLIGHT;
IF OBJECT_ID ('VOOS_AIRPLANE_TYPE','U') IS NOT NULL
    DROP TABLE dbo.VOOS_AIRPLANE_TYPE;
IF OBJECT_ID ('VOOS_AIRPORT','U') IS NOT NULL
    DROP TABLE dbo.VOOS_AIRPORT;

CREATE TABLE VOOS_AIRPORT (
	CODE			INT			NOT NULL,
	CITY			VARCHAR(15) NOT NULL,
	AIRPORT_STATE	VARCHAR(15)	NOT NULL,
	NOME			VARCHAR(15)	NOT NULL,
	PRIMARY KEY (CODE)
);

CREATE TABLE VOOS_AIRPLANE_TYPE (
	VOO_TYPE_NAME	VARCHAR(20)	NOT NULL,
	COMPANY			VARCHAR(20)	NOT NULL,
	MAX_SEATS		INT			NOT NULL,
	PRIMARY KEY (VOO_TYPE_NAME)
);

CREATE TABLE VOOS_FLIGHT (
	NUMBER		INT			NOT NULL,
	AIRLINE		VARCHAR(20)	NOT NULL,
	WEEKDAYS	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (NUMBER)
);

CREATE TABLE VOOS_FARE (
	CODE			INT			NOT NULL,
	FLIGHT_NUMBER	INT			NOT NULL,
	AMOUNT			INT			NOT	NULL,
	RESTRICTIONS	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (CODE, FLIGHT_NUMBER),
	FOREIGN KEY (FLIGHT_NUMBER) REFERENCES VOOS_FLIGHT (NUMBER)
);

CREATE TABLE VOOS_AIRPLANE (
	AIRPLANE_ID			INT			NOT NULL,
	TOTAL_NO_OF_SEATS	INT			NOT NULL,
	AIRPLANE_TYPE_NAME	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (AIRPLANE_ID),
	FOREIGN KEY (AIRPLANE_TYPE_NAME) REFERENCES VOOS_AIRPLANE_TYPE (VOO_TYPE_NAME)
);

CREATE TABLE VOOS_CAN_LAND (
	AIRTPORT_CODE		INT			NOT NULL,
	AIRPLANE_TYPE_NAME	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (AIRTPORT_CODE),
	FOREIGN KEY (AIRTPORT_CODE) REFERENCES VOOS_AIRPORT (CODE),
	FOREIGN KEY (AIRPLANE_TYPE_NAME) REFERENCES VOOS_AIRPLANE_TYPE (VOO_TYPE_NAME)
);

CREATE TABLE VOOS_FLIGHT_LEG (
	LEG_NO				INT		NOT NULL,
	SCH_DEP_TIME		TIME	NOT NULL,
	SCH_ARR_TIME		TIME	NOT NULL,
	AIRPORT_CODE_DEP	INT		NOT NULL,
	AIRPORT_CODE_ARR	INT		NOT NULL,
	FLIGHT_NUMBER		INT		NOT NULL,
	PRIMARY KEY (LEG_NO, FLIGHT_NUMBER),
	FOREIGN KEY (AIRPORT_CODE_DEP) REFERENCES VOOS_AIRPORT (CODE),
	FOREIGN KEY (AIRPORT_CODE_ARR) REFERENCES VOOS_AIRPORT (CODE),
	FOREIGN KEY (FLIGHT_NUMBER) REFERENCES VOOS_FLIGHT (NUMBER)
);

CREATE TABLE VOOS_LEG_INSTANCE (
	LEG_INSTANCE_DATE	DATE				NOT NULL,
	NO_OF_AVAI_SEATS	INT		DEFAULT 0	NOT NULL,
	DEP_TIME			TIME				NOT NULL,
	AIR_TIME			TIME				NOT NULL,
	AIRPLANE_ID			INT					NOT NULL,
	AIRPORT_CODE_ARR	INT					NOT NULL,
	AIRPORT_CODE_DEP	INT					NOT NULL,
	FLIGHT_LEG_NO		INT					NOT NULL,
	FLIGHT_NUMBER		INT					NOT NULL,
	PRIMARY KEY (LEG_INSTANCE_DATE, FLIGHT_LEG_NO, FLIGHT_NUMBER),
	FOREIGN KEY (AIRPLANE_ID) REFERENCES VOOS_AIRPLANE (AIRPLANE_ID),
	FOREIGN KEY	(AIRPORT_CODE_ARR) REFERENCES VOOS_AIRPORT (CODE),
	FOREIGN KEY	(AIRPORT_CODE_DEP) REFERENCES VOOS_AIRPORT (CODE),
	FOREIGN KEY (FLIGHT_LEG_NO, FLIGHT_NUMBER) REFERENCES VOOS_FLIGHT_LEG (LEG_NO, FLIGHT_NUMBER)
);

CREATE TABLE VOOS_SEAT (
	SEAT_NO				INT			NOT NULL,
	CUSTOMER_NAME		VARCHAR(20),
	C_PHONE				INT,
	LEG_INSTANCE_DATE	DATE		NOT NULL,
	FLIGHT_LEG_NO		INT			NOT NULL,
	FLIGHT_NUMBER		INT			NOT NULL,
	PRIMARY KEY (SEAT_NO, LEG_INSTANCE_DATE, FLIGHT_LEG_NO, FLIGHT_NUMBER),
	FOREIGN KEY (LEG_INSTANCE_DATE, FLIGHT_LEG_NO, FLIGHT_NUMBER) REFERENCES VOOS_LEG_INSTANCE (LEG_INSTANCE_DATE, FLIGHT_LEG_NO, FLIGHT_NUMBER)
);